### ISSUE TITLE
message box not disappearing

### ISSUE THREAD

**Issue by kamilkrzeminski** [kkarpieszuk/prior-price#124]
Hi, 
the following message box is stuck in wp-admin and can't be closed. 

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/31ba8e10-1e6d-485e-a1df-7a6e08999bec">

**Comment by kkarpieszuk** [comment]
sorry for the inconviniences. Please add this to your functions.php in theme folder:
```
$wcph_settings = get_option( 'wc_price_history_settings' );

$wcph_settings['first_history_scan'] = 2;

update_option( 'wc_price_history_settings', $wcph_settings );
```
visit your site once and then you can remove this. Then you should see info about scan being finished which you will be able to close. 


For debugging: do you recall what you did before this?

**Comment by kamilkrzeminski** [comment]
No problem, thanks for quick response. 

Unfortunately, I can't recall anything unusual what may have caused this behavior. Just installed the plugin and set it up.
