### ISSUE TITLE
"Day before product went on sale (excludes promotional price)" not working as expected

### ISSUE THREAD

**Issue by admirlju** [kkarpieszuk/prior-price#89]
### How the project is setup:
All products on the store are variable. The variation sale price gets update only via REST API, all sales are always timed (they have start and end date set, time portion of datetime is always 00:00).
We also update the stock on a daily basis via the REST API.

### The issue:
We have selected the "Day before product went on sale (excludes promotional price)", on the day of the sale this works correctly the previous day's price is shown, but the next day the minimum price becomes the current sale price.

### Investigating the code:
Looking through the code (WordPress and WooCommerce are not my primary environments, so I could be off).

First the condition `$timestamp >= ( $sale_start_timestamp - ( $days * DAY_IN_SECONDS ) ) && $timestamp <= $sale_start_timestamp` located in `HistoryStorage::get_minimal_from_sale_start` also includes history data of the day the sale started.

And this might be an issue because of `ProductUpdates::update_price_history` that gets triggered on `woocommerce_save_product_variation` hook. I assume this hook also gets triggered when we update the variation stock? If that is the case the price history will contain the reduced price and with that condition, which I mentioned before, it will pick it up when displaying the lowest price.

**Comment by kkarpieszuk** [comment]
@admirlju thank you for reporting this. Could you check the branch from this PR #90 if this works for you now as expected?

If you are not familiar with git cloning, using branches and builiding (npm, composer), I have prepared a zip with this version of the plugin.

[wc-price-history.zip](https://github.com/user-attachments/files/16066711/wc-price-history.zip)
